### ISSUE TITLE
AudienceNetwork causes compilation errors on Android

### ISSUE THREAD

**Issue by Drutol** [xamarin/FacebookComponents#101]
Hello, for past few days I've been trying to implement ads mediation in my Xamarin.Android app and the first service I wanted to use for this was Facebook. Unfortunately I've run into a multitude of different issues and in the end I've decided to ask here. My problem is:

```
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
1>  java.lang.RuntimeException: Translation has been interrupted
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
1>  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
1>  	at com.android.dx.command.dexer.Main.runDx(Main.java:289)
1>  	at com.android.dx.command.dexer.Main.main(Main.java:247)
1>  	at com.android.dx.command.Main.main(Main.java:94)
1>  Caused by: java.lang.InterruptedException: Too many errors
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
1>  	... 4 more
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2521,3): error : java.lang.RuntimeException :  Translation has been interrupted
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========
```

It could be caused by broken(?) desugar of java 8 as mentioned [here](https://github.com/xamarin/xamarin-android/issues/1738). It doesn't even work when I set min-sdk to 26... which is no go anyway.

The first NuGet version that causes this issue is: `4.22.0`, earlier ones don't work though as I'm guessing that Facebook deprecated older APIs.
The error occurs only when the components are actually used in code with such class for example:

```cs
    [Preserve(AllMembers = true)]
    public class FacebookCustomEventBanner : Java.Lang.Object, ICustomEventBanner
    {
        private AdView _adBanner;

        public void OnDestroy()
        {
            _adBanner?.Destroy();
        }
        ...
        public void RequestBannerAd(Context context,
            ICustomEventBannerListener listener,
            string serverParameter,
            AdSize size,
            IMediationAdRequest mediationAdRequest,
            Bundle customEventExtras)
        {
            _adBanner = new AdView(context, "<>", Xamarin.Facebook.Ads.AdSize.BannerHeight50);
            _adBanner.SetAdListener(new FacebookCustomEventBannerForwarder(listener, _adBanner));
            _adBanner.LoadAd();
        }
    }
```

Am I missing something obvious here? Or is it just impossible to use it right now?

> VS bug [#732196](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732196)

**Comment by aixiaozi** [comment]
Is there any updates? Just the same error.

```
3>  BindingLibraryDemo.Android -> C:\workspace\0121\BindingLibraryDemo\BindingLibraryDemo\BindingLibraryDemo.Android\bin\Debug\BindingLibraryDemo.Android.dll
3>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
3>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
3>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
3>COMPILETODALVIK : Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========
```

Attached is a project could reproduce this issue: [BindingLibraryDemo.zip](https://github.com/xamarin/FacebookComponents/files/2778339/BindingLibraryDemo.zip)

**Comment by aixiaozi** [comment]
Resolved my issue. Enable `desugar` via $(AndroidEnableDesugar) in my `.csproj`.

```
<AndroidEnableDesugar>true</AndroidEnableDesugar>
```
