### ISSUE TITLE
xamarin.facebok.android 5.0.3 com.facebook.CampaignTrackingReceiver exception

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/FacebookComponents#140]
I have just upgraded to xamarin.facebok.android 5.0.3 nuget and i am getting this error below. this is a typical proguard error. but i really dont get what is this class for? it looks like facebook ads sdk. I am only using facebook login. why i am getting this error? any idea?  what does facebook login has to do with this class?

java.lang.RuntimeException: Unable to instantiate receiver com.facebook.CampaignTrackingReceiver: java.lang.ClassNotFoundException: Didn't find class "com.facebook.CampaignTrackingReceiver" on path: DexPathList[[zip file "/data/app/myworkout.myworkout-yCRpXrcdvu53nMSAnreY5A==/base.apk"],nativeLibraryDirectories=[/data/app/myworkout.myworkout-yCRpXrcdvu53nMSAnreY5A==/lib/arm, /data/app/myworkout.myworkout-yCRpXrcdvu53nMSAnreY5A==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:3376)
  at android.app.ActivityThread.-wrap18
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
  at android.os.Handler.dispatchMessage(Handler.java:105)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6942)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.CampaignTrackingReceiver" on path:
  DexPathList[[zip file "/data/app/myApp.myApp-yCRpXrcdvu53nMSAnreY5A==/base.apk"],
  nativeLibraryDirectories=[/data/app/myApp.myApp-yCRpXrcdvu53nMSAnreY5A==/lib/arm,
  /data/app/myApp.myApp-yCRpXrcdvu53nMSAnreY5A==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3371)
    at android.app.ActivityThread.-wrap18
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6942)
    at java.lang.reflect.Method.invoke(Method.java:-2)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by EmilAlipiev** [comment]
no idea about this problem? it keeps throwing exception for me. previous versions didnt have this error

**Comment by SotoiGhost** [comment]
@EmilAlipiev is this still an issue?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
