### ISSUE TITLE
Crash when using 'Xamarin.Facebook.AudienceNetwork.Android' through adMob mediation

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/FacebookComponents#181]
I use admob mediation to display facebook ads (using Xamarin.Facebook.AudienceNetwork.Android v 5.10.1) and when a Facebook ad is displayed, I've got this crash :

```
java.lang.AbstractMethodError: abstract method "void com.facebook.ads.AdListener.onLoggingImpression(com.facebook.ads.Ad)"
 at com.facebook.ads.redexgen.X.TG.A04(:53786)
 at com.facebook.ads.redexgen.X.Kk.run(:40495)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:227)
 at android.app.ActivityThread.main(ActivityThread.java:7582)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
````
Can you do something about it ?

Thanks !

**Comment by mhdwaelanjo** [comment]
We can use the Meta Audience Network Mediation Adapter For The Google Mobile Ads SDK 
[Anjo.Android.GoogleAds.Mediation.FacebookAdapter](https://www.nuget.org/packages/Anjo.Android.GoogleAds.Mediation.FacebookAdapter/) (>= 6.16.0)
